In [1]:
print("Hello world")

Hello world

In [22]:
# Loading in a dataset
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
import pandas as pd

In [16]:
data = {
    "names": ["Dr Abc", "Mr BCD", "Ms DEF",]
}
df =pd.DataFrame(data)

In [17]:
df.head()

    names
0  Dr Abc
1  Mr BCD
2  Ms DEF

In [7]:
import re

In [21]:
df["cleanNames"] = df.names.apply(lambda x: re.sub(r"(Mr|Mrs|Dr|Ms)", "", x))
df

    names cleanNames
0  Dr Abc        Abc
1  Mr BCD        BCD
2  Ms DEF        DEF

In [24]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
encoder = LabelEncoder()

df["embarked_1HC"] = encoder.fit_transform(df["embarked"])

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embarked_1HC
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,2
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,2

In [28]:
# Functions
def sayHello():
    print("Hello")

In [29]:
sayHello()

Hello

In [34]:
def sayHelloV2(name="Bob"):
    print("Hello", name)

In [33]:
sayHelloV2(name="Nirosh")

Hello Nirosh

In [36]:
sayHelloV2()

Hello Bob

In [45]:
def addition(a,b):
    '''
    This is the guidance or docs for this function. 

    a is an int
    b is an int

    the output will be an int
    '''
    answer = a+b
    return answer

In [ ]:
addition()

In [43]:
X = addition(12,4)
print(X)

16

Task:
1. Create a function that a takes a DF and return no duplicates or NAs (remove them).
2. Create a function that goes through every numerical col, removes outliers and outputs a CLEAN DF and an OUTLIER DF.